[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending = "8s8Bqp4G6QmFW6gXn3vCFyWYDwiWixAHUjo4wsr6dftc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
